/**
 * Per-DO-class wrapper codegen (PRD amendment A2).
 *
 * Emits one wrapper module per DO class the customer marked for sharding.
 * Each wrapper transparently prepends the per-PR scope key to every
 * `idFromName` and `getByName` call, so the customer's user code can keep
 * referencing `env.ChatRoom` without knowing it's been wrapped.
 *
 * The customer's bundle is expected to import from `__raft_wrappers__/CLASS.js`
 * (see `@raft/do-cleanup` helper in the docs). Slice D ships the wrapper
 * modules; the customer-side import is a documented convention.
 */
import type { BundleModule } from './types.ts';

const WRAPPER_DIR = '__raft_wrappers__';

const wrapperSource = (className: string, scope: string): string =>
  `// AUTO-GENERATED by raft bundle-rewriter — do not edit.
//
// Wraps the customer DO namespace binding so every \`idFromName\` and
// \`getByName\` call is silently scoped to this PR (\`${scope}\`). Imported
// by the customer's bundle as:
//
//     import { wrap as wrap${className} } from './${WRAPPER_DIR}/${className}.js';
//     const ns = wrap${className}(env.${className});
//     ns.idFromName('roomA') === env.${className}.idFromName('${scope}:roomA')
//
// Equivalent to manually prefixing every name. Required because Cloudflare
// has no list-by-prefix on DO namespaces — the per-PR teardown step relies
// on every shard ID being recorded explicitly (PRD amendment A1).
const SCOPE = ${JSON.stringify(scope)};
const scoped = (name) => SCOPE + ':' + name;

class WrappedNs {
  constructor(ns) { this.ns = ns; }
  idFromName(name) { return this.ns.idFromName(scoped(name)); }
  idFromString(s) { return this.ns.idFromString(s); }
  newUniqueId(opts) { return this.ns.newUniqueId(opts); }
  get(id) { return this.ns.get(id); }
  jurisdiction(j) { return new WrappedNs(this.ns.jurisdiction(j)); }
}

export const wrap = (ns) => new WrappedNs(ns);
`;

export const generateWrapperModules = (
  doClassNames: readonly string[],
  scope: string,
): BundleModule[] =>
  doClassNames.map((className) => ({
    name: `${WRAPPER_DIR}/${className}.js`,
    content: wrapperSource(className, scope),
    contentType: 'application/javascript+module',
  }));

export const wrapperImportPath = (className: string): string => `./${WRAPPER_DIR}/${className}.js`;
